### ISSUE TITLE
Problem with string with argument event

### ISSUE THREAD

**Issue by Piero87** [arcturial/arduino-event#1]
Hi,
This library is amazing, and very very simple to use, i have only one problem, i want pass a String to the argument Event, in this way:

```
                String str = "123-45.0";
                ev_object.extra = str;
```

But give me this error:

```
cannot convert 'String' to 'const char*' in assignment
```

how i can do to fix this problem? i want pass a string that i elaborate previously with some sensor, then in the trigger function i will split this string for this "-" delimeter to get the two value back, how i can do?

Thank you very much

**Comment by arcturial** [comment]
You can cast it to a char

``` cpp
char char_arr[str.length];
str.toCharArray(char_arr, str.length());
```

Let me know if that is what you had in mind.

**Comment by Piero87** [comment]
Thanks for your answer, but give me this error:

```
Description Resource    Path    Location    Type '<unresolved overloaded function type>'
```

On this line:

```
char char_arr[str.length];
```

and this error:

```
cannot convert 'String' to 'const char*' in assignment
```

on this line:

```
ev_object.extra = str;
```

**Comment by arcturial** [comment]
Try changing this line

``` cpp
char char_arr[str.length];
```

to

``` cpp
char char_arr[str.length()];
```

I accidentally forgot the ()

**Comment by arcturial** [comment]
also, change 

``` cpp
ev_object.extra = str;
```

to

``` cpp
ev_object.extra = char_arr;
```

The event object takes a character array instead of a string. You should be able to cast it back and forth depending on your needs.

**Comment by Piero87** [comment]
Thank you very much now works!
